export const hotelNames = [
  "Pasin Traditional Hotel",
  "Espinas Palace Hotel",
  "Parsian Azadi Hotel",
  "Tehran Grand Hotel",
  "Firouzeh Heritage Hostel",
  "Remis Hotel",
  "RagRug Hostel",
  "Abbasi Hotel",
  "Safir Hotel",
  "Dad Hotel",
  "Moshir al-Mamalek Garden Hotel",
  "Pars Hotel",
  "Zandiyeh Hotel",
  "Shiraz Grand Hotel",
  "Mashhad Pars Hotel",
  "Darvishi Royal Hotel",
  "Kish International Hotel",
  "Qeshm Eram Hotel",
  "Tabriz International Hotel",
  "Kerman Akhavan Hotel",
];

export const roomNames = [
  "Single Room",
  "Double Room",
  "Triple Room",
  "Quad Room",
  "Queen Room",
  "King Room",
  "Twin Room",
  "Hollywood Twin Room",
  "Suite",
  "Luxury Room",
  "Resort Room",
  "Boutique Room",
];
