export const hotelComments = [
  "The view from the balcony was absolutely breathtaking!",
  "Rooms were spacious, clean, and beautifully decorated.",
  "Service was impeccable—staff made sure we had everything we needed.",
  "The breakfast buffet had an incredible selection of fresh, delicious food.",
  "The swimming pool was pristine and perfect for a relaxing swim.",
  "The spa treatments were top-notch—best massage I've had in years!",
  "The hotel’s design was elegant and modern, making the stay feel luxurious.",
  "The beds were incredibly comfortable—I slept like a dream!",
  "The location is fantastic, close to all the main attractions.",
  "The rooftop bar had amazing views and delicious cocktails.",
  "The staff was friendly and always greeted us with a smile.",
  "The garden area was peaceful and beautifully maintained.",
  "The hotel restaurant offered gourmet dishes that were absolutely delicious.",
  "The ambiance was cozy yet sophisticated—perfect for a getaway.",
  "Room service was prompt, and the food was excellent.",
  "The WiFi was strong and reliable throughout the entire stay.",
  "The gym had great equipment and a refreshing atmosphere.",
  "The lobby smelled divine and had a welcoming feel.",
  "The check-in process was smooth and quick—no waiting at all!",
  "I loved the little details, like complimentary chocolates and welcome drinks!",
];

export const managerReplies = [
  "Thank you so much for your kind words!",
  "We truly appreciate your positive feedback!",
  "Your support means the world to us!",
  "Thank you for choosing us—we’re grateful!",
  "We appreciate your thoughtful review!",
  "It’s wonderful to hear such kind words—thank you!",
  "Your satisfaction is our greatest reward—thank you!",
  "Thank you for sharing your wonderful experience!",
  "We’re so thankful for your kind comments!",
  "Your feedback motivates us—thank you!",
  "Thank you! We’re delighted you enjoyed your stay!",
  "We sincerely appreciate your support!",
  "It’s guests like you that make our work so fulfilling—thank you!",
  "Thank you for your glowing review!",
  "We’re honored by your kind words—thank you!",
  "Thank you for being part of our journey!",
  "Your appreciation means a lot—thank you!",
  "We’re deeply grateful for your encouragement!",
  "Thank you for your generous praise!",
  "It’s always a pleasure to serve wonderful guests like you!",
];
